import "./globals.css";

export const metadata = {
  title: "Gig Media",
  description: "Generated by Gig Media",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
